name: "Changelog - Update Unreleased"

###################################################################
# WARNING - THIS ACTION WILL PUSH COMMIT DIRECTLY INTO REPOSITORY #
###################################################################

on:
  push:
    branches:
      - 1.x

jobs:
  changelog-update-unreleased:
    name: "Changelog - Update Unreleased"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Restore Automation cache"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.automation
          key: "${{ runner.os }}-automation-"
          restore-keys: |
            ${{ runner.os }}-automation-

      - name: "Update CHANGELOG"
        uses: "docker://aeonphp/automation:latest"
        env:
          AEON_AUTOMATION_GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          entrypoint: "/composer/vendor/bin/automation"
          args: "changelog:generate ${{ github.repository }} --github-file-update-path=CHANGELOG.md --skip-from=\"dependabot[bot]\" --skip-from=\"aeon-automation\""
