name: "Tests"

on:
  pull_request:
  push:
    branches:
      - "1.x"
  schedule:
    - cron:  '0 8 * * *'

jobs:
  tests:
    name: "Tests"

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php-version:
          - "8.1"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: pcov
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1

      - name: "Cache Phive dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.phive
          key: "${{ runner.os }}-phive-${{ hashFiles('**/phars.xml') }}"
          restore-keys: |
            ${{ runner.os }}-phive-

      - name: "Get Composer Cache Directory"
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: "Cache Composer dependencies"
        uses: "actions/cache@v2"
        with:
          path: |
            ${{ steps.composer-cache.outputs.dir }}
            ~/.phive
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}"
          restore-keys: |
            php-${{ matrix.php-version }}-composer-

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Test"
        run: "composer test"
